[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wireshark_fieldbus_io"
version = "0.2.1"
description = "Extract fieldbus IO data from Wireshark capture files."
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [{ name = "mrBrutus" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Topic :: System :: Networking",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
dependencies = ["pyshark"]

[project.urls]
Repository = "https://github.com/mrBrutus/wireshark_fieldbus_io.git"
Changelog = "https://github.com/mrBrutus/wireshark_fieldbus_io/blob/main/CHANGELOG.md"
Issues = "https://github.com/mrBrutus/wireshark_fieldbus_io/issues"
