[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "async_dfd"
version = "0.1.16"
description = "A library for async accelerate based on gevent coroutine in python."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Haoyu Wang", email = "Haoyu_Wang_1103@outlook.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "gevent", 
    "tabulate",
    "tenacity",
    "trio"
]

[tool.setuptools.packages.find]
where = ["."]