[tool.poetry]
name = "sphinx_feature_flags"
version = "1.0.9"
description = "This Sphinx extension allows for the `feature-flag` directive to hide/show content based on build-time flags."
authors = ["Xsolla Backend <xbe@xsolla.com>", "Dylan Hunt <d.hunt@xsolla.com>"]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Build Tools",
    "Framework :: Sphinx :: Extension"
]

[tool.poetry.dependencies]
python = ">=3.10"
sphinx = ">=7.3.7"  # Confirmed working in 8.1.3

[tool.poetry.urls]
Homepage = "https://github.com/Unidocs1/sphinx_feature_flags"
Issues = "https://github.com/Unidocs1/sphinx_feature_flags/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
