[package]
name = "exrio"
version = "0.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "exrio"
crate-type = ["cdylib"]

[dependencies]
exr = "1.73.0"
half = "2.4.1"
numpy = { version = "0.23.0", features = ["half"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1.12.0"

[dependencies.pyo3]
version = "0.23"
features = ["extension-module", "abi3", "abi3-py39"]

