[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rosagents"
version = "0.0.1"
description = "ðŸ¤— rosagents: a barebones library for uas and robotics agents. Agents write python code to call tools or orchestrate other agents."
authors = [
  { name="jerry zhang", email="jerry.zhang.bill@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchaudio",
    "torchvision",
    "transformers>=4.0.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "pandas>=2.2.3",
    "jinja2>=3.1.4",
    "pillow>=11.0.0",
    "markdownify>=0.14.1",
    "gradio>=5.8.0",
    "duckduckgo-search>=6.3.7",
    "python-dotenv>=1.0.1",
    "e2b-code-interpreter>=1.0.3",
    "litellm>=1.55.10",
]

[project.optional-dependencies]
test = [
    "pytest>=8.1.0",
    "sqlalchemy"
]

[[tool.poetry.source]]
name = "private"
url = "http://13.251.243.197:8080/simple"
default = true