[project]
name = "omproxy"
dynamic = ["version"]
description = "An open source proxy for MCP servers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logfire>=2.6.2",
    "mcp>=1.1.0",
]

[tool.hatch.version]
path = "src/omproxy/__init__.py"

[project.scripts]
omproxy = "omproxy.cli:main"

[dependency-groups]
dev = [
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.8.2",
]


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.uv.sources]
mcp = { git = "https://github.com/modelcontextprotocol/python-sdk.git", rev = "main" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
