[project]
name = "describe-dataset"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.18"
dependencies = [
    "fire>=0.7.0",
    "pillow>=11.1.0",
    "pyyaml>=6.0.2",
]

[tool.setuptools]
license-files = []