[project]
name = "sweepystats"
version = "0.0.9"
authors = [
  { name="Benjamin Chu", email="benchu99@hotmail.com" },
]
description = "Python package to perform the statistical sweep operation on symmetric numpy matrices"
license = {file = "LICENSE"}
keywords = ["sweep", "matrix inverse", "determinant", "regression", "ANOVA"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy>=1.20",
  "scipy>=1.10.1",
  "tqdm>=4.0",
  "pandas>=1.0",
  "patsy>=0.5"
]

[project.urls]
Homepage = "https://github.com/biona001/sweepystats"
Documentation = "https://biona001.github.io/sweepystats"
Issues = "https://github.com/biona001/sweepystats/issues"

[tool.poetry.dependencies]
statsmodels = ">=0.13"

[tool.setuptools]
packages = ["sweepystats"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
