[tool.poetry]
name = "agentic-workflow"
version = "0.0.7"
description = "Agentic Flow is a platform for creating, managing, and executing AI workflows."
authors = ["Hari Narayanan <hari@trata.ai>"]
packages = [
    { include = "agentic_workflow" },
]
include = [
    "alembic/**/*",
    "alembic.ini"
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
alembic = "^1.13.1"
python-dotenv = "^1.0.0"
uvicorn = "^0.30.0"
psycopg2-binary = "^2.9.9"
sqlmodel = "^0.0.22"
asyncpg = "^0.30.0"
greenlet = "^3.1.1"
starlette = ">=0.40.0"
jsonata-python = "^0.5.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
env_files = [ ".env" ]
asyncio_mode = "auto"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-asyncio = "^0.24.0"
httpx = "^0.27.0"
pytest-dotenv = "^0.5.2"
aiosqlite = "^0.19.0"

[tool.poetry.scripts]
prod = "agentic_workflow.main:run"
dev = "agentic_workflow.main:run_dev"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 
