[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hyap-auth-manager"
version = "0.0.4"
authors = ["Hanif Yuli Abdillah P <hanifabd23@gmail.com>"]
repository = "https://github.com/hanifabd/hyap-auth-manager"
keywords = ["auth", "authentication", "access", "key", "web", "asymmetrics", "symmetrics"]
description = "Python package for managing authentication keys based on python."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.7"
cryptography = "^39.0.1"
pyjwt = "^2.5.0"

[tool.poetry.dev-dependencies]
