[tool.poetry]
name = "doimbu"
version = "0.6.1"
description = "Lightweight tool for docker image creation with multiple variants."
authors = [ "alex carvalho <alex.carvalho.data@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://gitlab.com/alex-carvalho-dockeration/doimbu"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Version Control :: Git",
]
include = [
    "docs",
    "img",
    "tests"
]

[tool.poetry.urls]
"Changelog" = "https://gitlab.com/alex-carvalho-dockeration/doimbu/-/blob/master/CHANGELOG.md"
"Issues" = "https://gitlab.com/alex-carvalho-dockeration/doimbu/-/issues"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
mypy = "^1.13.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
