
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olab_open_api"
version = "0.0.4"
description = "call openapi directly without using complete sdk"
authors = [
    { name = "nik_opinionlabs", email = "nik@opinionlabs.xyz" }
]
dependencies = []