[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "athreading"
version = "0.2.1"
description = "Asynchronous threading package for Python"
readme = "README.md"
authors = ["Callan Gray <cal.j.gray@gmail.com>"]
license = "BSD-3-Clause"
homepage = "https://github.com/calgray/athreading"
repository = "https://github.com/calgray/athreading.git"
packages = [{ include = "athreading", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.test.dependencies]
pytest = ">=7,<9"
pytest-cov = ">=4,<7"
pytest-mypy = "^0.10.0"
pytest-mock = "^3.14.0"
pytest-asyncio = ">=0.20.3,<0.26.0"
pytest-benchmark = "^5.1.0"
isort = "^5.10.1"
pre-commit = ">=3.0.4,<5.0.0"
black = ">=23.1,<25.0"
flake8 = ">=6,<8"
flake8-docstrings = "^1.6.0"
flake8-pyproject = "^1.2.2"
threaded = "^4.2.0"
typing_extensions = { python = "3.13", version = ">4.12.0" }

[tool.mypy]
disallow_any_explicit = true
disallow_any_generics = true
warn_unreachable = true
warn_unused_ignores = true
disallow_untyped_defs = true
exclude = [".venv/"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.flake8]
max-line-length = 99
exclude = [
    'tests/*'
]
extend-ignore = [
    'E203',
    'D200', # One-line docstring should fit on one line with quotes
    'D205', # 1 blank line required between summary line and description
    'D415', # First line should end with a period, question mark, or exclamation point
    'D105', # Missing docstring in magic method
    # D1,  # Uncomment to disable enforcing docstrings
]
required-plugins = [
    'flake8-docstring'
]
docstring-convention = 'google'
# per-file-ignores =
#     tests/*:D100,D104  # Uncomment to disable enforcing module-level docstring in tests/


[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-v",
    "-p",
    "no:warnings",
    "--cov=athreading",
    "--cov-report=html",
    "--doctest-modules",
    "--benchmark-disable",
    "--ignore=athreading/__main__.py"
]
