[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "grscheller.fp"
authors = [
    { name = "Geoffrey R. Scheller", email = "geoffrey@scheller.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed"
]
dependencies = []
dynamic = ["version", "description"]
keywords = [
    "functional", "functional programming", "fp",
    "monad", "iterators",
    "maybe", "either",
    "lazy", "non-strict"
]

[project.optional-dependencies]
test = [
    "pytest >=8.3",
    "grscheller.circular-array >=3.8.1, < 3.9",
    "grscheller.datastructures >=0.24.0, < 0.25"
]

[project.urls]
Source = "https://github.com/grscheller/fp"
Changelog = "https://github.com/grscheller/fp/blob/main/CHANGELOG.md"
Documentation = "https://grscheller.github.io/grscheller-pypi-namespace-docs/fp"

[tool.flit.sdist]
exclude = ["dist", "docs", ".gitignore", ".mypy_cache"]

[tool.pylsp-mypy]
enabled = true
live-mode = true
strict = true
report_progress = true

[tool.mypy]
enable_incomplete_feature = ["NewGenericSyntax"]
implicit_reexport = false
local_partial_types = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
consider_namespace_packages = true

[tool.ruff]
target-version = "py313"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
