[build-system]
requires = ["setuptools>=61.0", "loguru==0.7.3"]
build-backend = "setuptools.build_meta"

[project]
name = "AnotherSpace"
version = "0.0.5"
authors = [
  { name="William Adams", email="williamadams.aurora@gmail.com" },
]
description = "AnotherSpace team's internal library"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/WilliamAdamsWAG/AnotherSpace"
Issues = "https://github.com/WilliamAdamsWAG/AnotherSpace/issues"