[tool.poetry]
name = "parlant-qna"
version = "0.2.2"
description = "A questions and answers tool service for Parlant"
authors = ["Yam Marcovitz <yam@emcie.co>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.scripts]
parlant-qna = "parlant_qna.cli:main"

[tool.poetry.dependencies]
python = "^3.10"
parlant = "^1.4"
pyright = "^1.1.391"
structlog = "^24.4.0"
colorama = "^0.4.6"


[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.0"

[tool.pyright]
strict = ["**/*.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
