[project]
dependencies = [
  "click>=8.1.8",
  "platformdirs>=4.3.6",
  "promptic>=4.0.1",
  "rich>=13.9.4",
]
description = "Add your description here"
name = "broski"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[project.scripts]
homes = "homes:main"
