[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "searchlite"
version = "0.8.8"
description = "fastest web search backed by selenium"
authors = [ "Kammari Santhosh",]
readme = "README.md"
license = "MIT License"
repository = "https://github.com/santhosh/"
keywords = [ "",]
include = []
[[tool.poetry.packages]]
include = "searchlite"

[tool.poetry.dependencies]
python = "^3.10"
parselite = "^0.3.13"
