[project]
version = "0.10.1"
name = "pyNlple"
description = "NLP procedures in python brought to you by YouScan."
readme = "README.md"
license = {text = "MIT Licence"}
requires-python = ">=3.8"
dependencies = [
    "emoji>=0.5.0",
    "numpy>=1.18",
    "pandas>=0.19.0",
    "requests>=2.32.3",
    "scikit-learn>=0.22",
]
authors = [
    { name = "YouScan Data Science team, NLP guild.", email = "ds@youscan.io" },
]

[dependency-groups]
es = [
    "elasticsearch~=8.17.0",
]

[tool.setuptools]
license-files = []