[project]
name = "pond-agent"
version = "0.1.3"
description = "AI agents for Pond"
authors = [
    {name = "bill@cryptopond.xyz"}
]
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.5.0",
    "torch>=2.0.0",
    "tqdm>=4.0.0",
    "anthropic>=0.40.0",   
    "openai>=1.57.0",
    "python-dotenv>=1.0.0",
    "xgboost>=2.0.0",
    "pyarrow>=18.0.0",
    "polars>=1.16.0",
    "openpyxl>=3.1.0",
    "tabulate",
    "requests",
    "playwright>=1.40.0",
    "aiofiles",
    "aiohttp>=3.9.1",
    "beautifulsoup4"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.6.0",
    "pytest-cov",
    "build",
    "twine"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"

[tool.ruff]
select = ["E", "F", "B"]
ignore = []
line-length = 98
target-version = "py311"
