[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.0",
]

[project]
authors = [
    { email = "johannes-programming@mailfence.com", name = "Johannes" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = []
description = "BASEoriginaldata"
keywords = []
name = "BASEoriginaldata"
readme = "README.rst"
requires-python = ">=3.7"
version = "2.0.0.dev3"

[project.license]
file = "LICENSE.txt"

[project.urls]
Documentation = "https://pypi.org/project/BASEoriginaldata"
Download = "https://pypi.org/project/BASEoriginaldata/#files"
Source = "https://github.com/johannes-programming/BASEoriginaldata"
