[project]
authors = [{name = "Harlan D Heilman", email = "harlan.heilman@wsu.edu"}]
dependencies = [
  "numpy>=1.23.5,<2.0.0",
  "pandas>=2.0,<2.2.3dev0",
  "scipy>=1.7.0,<1.14.0",
  "matplotlib>=3.10.0",
  "numba>=0.60.0",
]
description = "Fitting in python made easy"
license = "GPL-2.0"
name = "ezfit"
readme = "README.md"
repository = "https://github.com/WSU-Carbon-Lab/ezfit"
requires-python = ">=3.10"
version = "0.1.12"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
