[tool.poetry]
name = "nyust-sso-client"
version = "0.2.0"
description = "A client for NYUST SSO system, providing authenticated access and common API calls."
authors = ["jason9294 <jason9294@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "nyust_sso" }]


[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
pydantic = "^2.10.4"
pytz = "^2024.2"
colorlog = "^6.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
