[tool.poetry]
name = "log-folder"
version = "0.1.0"
description = ""
authors = ["Huzaifa Naeem <huzaifa.naeem@datumlabs.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
