
[tool.poetry]
name = "leap-model-rebuilder"
version = "0.1.8"
description = ""
license = "MIT"
readme = "README.md"
repository = "https://github.com/tensorleap/leap-model-rebuilder"
homepage = "https://github.com/tensorleap/leap-model-rebuilder"
authors = ["dorhar <doron.harnoy@tensorleap.ai>"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
protobuf = "^3.19.6"
tensorflow = {version = "2.15.0", markers = "platform_machine  == 'x86_64'"}
tensorflow-macos = {version = "2.15.0", markers = "platform_machine  == 'arm64'"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
grappa = "^1.0.1"
pylint-pytest = "^1.1.2"
pytest-cov = "^3.0.0"
pylint = "^2.8.1"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = ["ignore:.*the imp module.*:DeprecationWarning"]
