[build-system]
build-backend = "poetry.core.masonry.api"

requires = [ "poetry-core" ]

[tool.poetry]
name = "vitaleey-cli"
version = "1.2.2"
description = "Vitaleey CLI"
authors = [ "Vitaleey" ]
readme = "README.md"
packages = [ { include = "vitaleey_cli", from = "." } ]
package-mode = true

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
jinja2 = "^3.1.4"
click = "^8.1.7"
tomli = "^2.0.1"
pyyaml = "^6.0.1"
python-gitlab = "^5.1.0"
python-dateutil = "^2.9.0.post0"
cryptography = "^43.0.0"

[tool.poetry.group.dev.dependencies]
coverage = "^7.5.1"
black = "^24.4.2"
isort = "^5.13.2"
bandit = "^1.7.9"
flake8 = "^7.1.0"
flake8-black = "^0.3.6"
flake8-isort = "^6.1.1"
flake8-pyproject = "^1.2.3"
flake8-debugger = "^4.1.2"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"

[tool.poetry.scripts]
vitaleey = "vitaleey_cli.cli:main"

[tool.isort]
profile = "black"
known_first_party = "vitaleey_cli"

[tool.flake8]
max-line-length = 119
max-complexity = 15
# When adding a flake8 error to ignore, please describe the error in a comment line.
# List of docstring errors: http://www.pydocstyle.org/en/stable/error_codes.html
ignore = [
    "W503", # Line break occurred before a binary operator (old pep8)
]

[tool.black]
line-length = 119
target-version = ['py312']

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = [ "vitaleey_cli/tests" ]

[tool.vitaleey.application]
python_registry = "pypi"
