[tool.poetry]
name = "dssatsim"
version = "0.1.3"
description = "Simple saptiotemporal DSSAT simulator"
authors = ["JK <kpodojos@msu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "2.2.2"
pygeohash = "1.2.0"
shapely = "2.0.5"
pyproj = "3.6.1"
geopandas = "0.14.4"
fastparquet = "2024.5.0"
dssattools = "2.1.4"
python-dotenv = "1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
