[package]
name = "anyreader-walker"
version = "0.2.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A library for reading streams of compressed and uncompressed data without knowing the format in advance"
readme = "README.md"

[dependencies]
anyreader = { path = "../anyreader", version = "0.2.0" }
tar = "0.4.43"
zip = "2.2.2"
bytes = "1.9.0"
smallvec = "1.13.2"

[dev-dependencies]
anyreader = { path = "../anyreader", features = ["test-utils"] }
zstd = "0.13.2"
